### ISSUE TITLE
privileges missing?

### ISSUE THREAD

**Issue by bmullan** [alswl/excalidraw-collaboration#1]
Just tried to install via the README steps.

I execute the following and get what looks like repository access permission errors?

> $ **sudo git clone --recursive git@github.com:alswl/excalidraw-collaboration.git**  
> Cloning into 'excalidraw-collaboration'...
> *git@github.com: Permission denied (publickey)*.
> **fatal**: Could not read from remote repository.
>  
> Please make sure you have the correct access rights
> and the repository exists.

got any idea's whats going on.

thanks
brian

**Comment by alswl** [comment]
Hi there, it was simple to solve.

Because Github have two way clone a repo, one way is using SSH keys(SSH protocol), and another way is using HTTPS(HTTP protocol). The error message shows you did not set a Git public key to Github.

How to fix it? There are two solutions:

- Update your public SSH key to https://github.com/settings/keys
- Replace the repo url with HTTPS Style in `.gitmodules`.
